service:
  type: web
  name: 1-x-bet
  env: python
  plan: free
  buildCommand : "pip install -r requirements.txt"
  startCommand : "gunicorn --chdir src app:service"
  envVars:
    - key: Python_version
      value: 3.10.0
    - key: Another_key
      value: Another_value
